name: trainingtester

channels:
    - https://conda.anaconda.org/conda-forge
    - https://conda.anaconda.org/joshburt
    - https://conda.anaconda.org/ae5-admin

dependencies:
    - python=3.8.15
    - ipykernel
    - mlflow=2.0.1
    - make
    - virtualenv
    - pip
    - anaconda.enterprise.server.common.sdk>=0.3
    - ae5-tools
    - anaconda.enterprise.server.contracts>=0.9.3
    - anaconda.enterprise.mlflow.plugin.backend>=0.1.2
