{% set name = "anaconda.enterprise.mlflow.plugin.project_backend" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python>=3.8
    - setuptools
  run:
    - python>=3.8
    - mlflow=2.0.1
    - ae5-tools
    - anaconda.enterprise.server.contracts>=0.9.3
    - anaconda.enterprise.server.common.sdk

about:
  home: https://github.com/shapeandshare/anaconda.enterprise.mlflow.plugin.project_backend
  summary: "MLFlow Backend Plugin For Anaconda Enterprise"
  license: BSD
  license_file: LICENSE
