{% set name = "mlflow-adsp" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python>=3.8
    - setuptools
  run:
    - python>=3.8
    - mlflow=2.0.1
    - ae5-tools
    - anaconda.enterprise.server.contracts>=0.10
    - anaconda.enterprise.server.common.sdk

about:
  home: https://github.com/shapeandshare/mlflow-adsp
  summary: "MLFlow Plugin For Anaconda Enterprise"
  license: Apache-2.0
  license_file: LICENSE
